### ISSUE TITLE
Update latest libdns

### ISSUE THREAD

**Issue by Potat0000** [nickygerritsen/caddy-powerdns#1]
As libdns/powerdns#4 been merged and `v0.1.2` has been added, it's now working fine for my use case. Looking forward to upgrade libdns package and could push to [caddy-dns organization](https://github.com/caddy-dns) soon.

Thank you for your excellent work!

**Comment by nickygerritsen** [comment]
Done! I don't know how we will get this to the main caddy-dns org though.

**Comment by Potat0000** [comment]
> I don't know how we will get this to the main caddy-dns org though.

Is it possible to change the [go.mod](https://github.com/nickygerritsen/caddy-powerdns/blob/79c99dcd21421184998486265ad3242f79b8bda6/go.mod#L1) if it can't be pushed to Caddy at the moment? It doesn't match the repository name now, causing xcaddy to report an error.

**Comment by nickygerritsen** [comment]
I created [this topic](https://caddy.community/t/created-new-dns-module-powerdns/18816) to see if we can get it moved.

**Comment by Potat0000** [comment]
Great! Looking forward to moving to an official organization soon!

**Comment by nickygerritsen** [comment]
See https://github.com/caddy-dns/powerdns.

I will close this repo, since that is now the one to use.
